/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brochurepdf;

import java.util.Date;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;

import com.itextpdf.text.Font;
import com.itextpdf.text.Image;

import com.itextpdf.text.Paragraph;

import java.io.IOException;

/**
 * Editer une brochure
 *
 * @author Oualali.A
 * @version 1.0
 */
public class editerPDF {

    private static String FILE;
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    private static String image;

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    /**
     *
     * @param document le fichier sue lequelle different traitemens seront
     * execute
     */
    public static void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }

    /**
     *
     * @param document le fichier sue lequelle different traitemens seront
     * execute
     * @throws Exception peur retourne une exception DocumentException
     */
    public static void addTitlePage(Document document)
            throws Exception {

        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Brochure", catFont));
        addEmptyLine(preface, 10);
        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph(
                "c'est une brochure qui permet de definir les equipements en fonction des bateau",
                smallBold));

        document.add(preface);
        // Start a new page
        document.newPage();
    }

    /**
     *
     * @param doc le fichier sue lequelle different traitemens seront execute
     * @param document chemin ou le fichier sera cree
     * @throws Exception peut retourne une Exception du type BadElementException
     * et DocumentException
     */
    public static void addContent(Document doc, String document) throws Exception {

        Paragraph subPara = new Paragraph(document);
        doc.add(subPara);

    }

    /**
     *
     * @param doc le fichier sue lequelle different traitemenbs seront execute
     * @param path chemin ou le fichier sera cree
     * @throws Exception peut retourne une Exception du type BadElementException
     * et DocumentException
     */
    public static void addImage(Document doc, String path) throws Exception {

        Image front = Image.getInstance(path);
        doc.add(front);
    }

    /**
     *
     * @param paragraph pour ecrire du texte
     * @param number le nombre de saut de ligne
     */
    public static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

    /**
     *
     * @return le chemin pour cree un fichier
     */
    public static String getFILE() {
        return FILE;
    }

    /**
     *
     * @param FILE modifie le chemin pour cree le fichier
     */
    public static void setFILE(String FILE) {
        editerPDF.FILE = FILE;
    }

}
