/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brochurepdf;

import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;

/**
 * Traitement pour editer une brochure
 *
 * @author Oualali.A
 */
public class Traitement_editer extends javax.swing.JInternalFrame {

    /**
     * Creates new form Traitement_editer
     */
    public Traitement_editer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editer une brochure");

        jButton1.setText("Editer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pour editer une brochure cliquez sur editer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     *
     * @param evt editer
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        passerelle p = new passerelle();
        editerPDF epdf = new editerPDF();

        try {
            Document document = new Document();
            String chemin = JOptionPane.showInputDialog("saisir le chemin du fichier n'oubliez pas de nommez votre fichier a la fin");
            PdfWriter.getInstance(document, new FileOutputStream(chemin));
            document.open();
            epdf.addMetaData(document);
            epdf.addTitlePage(document);

            epdf.addContent(document, "-------------BATEAU VOYAGEUR------------");
            for (BateauVoyageur b : p.chargerLeBateauVoyageur()) {

                epdf.addContent(document, "" + b + "\n");

                epdf.addImage(document, b.getImagebatvoy());

            }
            epdf.addContent(document, "-------------BATEAU FRET----------------");
            for (Fret f : p.chargerLeBateauFret()) {

                epdf.addContent(document, "" + f + "\n");
                epdf.addImage(document, f.getImg());
            }
            JOptionPane.showMessageDialog(null, "fichier creez avec succes");
            document.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
